### ISSUE TITLE
Json Exception while querying artist (XML received)

### ISSUE THREAD

**Issue by ReIaxo** [Zastai/MetaBrainz.MusicBrainz#64] opened 2024-01-06 13:51 UTC
Hi. I get the following error now for the first time. It occurs while querying 
```
Ed Sheeran b8a7c51f-362c-4dcb-a259-bc6e0095f0a6
Calvin Harris 8dd98bdc-80ec-4e93-8509-2f46bafc09a7
Sam Smith 5a85c140-dcf9-4dd2-b2c8-aff0471549f3
```

I use this call
```
Query.LookupArtist(new Guid("b8a7c51f-362c-4dcb-a259-bc6e0095f0a6"), Include.UrlRelationships)
```
for Ed Sheeran in example.

```
System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
2
   at MetaBrainz.Common.Json.JsonUtils.GetJsonContentAsync[T](HttpResponseMessage response, JsonSerializerOptions options, CancellationToken cancellationToken)
   at MetaBrainz.MusicBrainz.Query.PerformRequestAsync[T](String entity, String id, String extra, CancellationToken cancellationToken)
   at MetaBrainz.MusicBrainz.Query.LookupArtistAsync(Guid mbid, Include inc, Nullable`1 type, Nullable`1 status, CancellationToken cancellationToken)
   at MetaBrainz.Common.AsyncUtils.ResultOf[T](Task`1 task)
   at MetaBrainz.MusicBrainz.Query.LookupArtist(Guid mbid, Include inc, Nullable`1 type, Nullable`1 status)
   at ArtistQuery.ArtistQueryHelper.LookupArtist(String mbId) in /home/relaxo/BitBucket/add-event-yambs/ArtistQueryHelper.cs:line 124
   at AddEventYambs.Scraper.ScraperController.<>c__DisplayClass8_5.<ScrapeAll>b__5(IArtist possibleMatch) in /home/relaxo/BitBucket/add-event-yambs/Scraper/ScraperController.cs:line 127
```

**Comment by Zastai** [comment] 2024-01-06 13:57
If this is with the newly released version, could you try enabling the TraceSource for Query and JsonUtils? That should then give you the responses received.

I fear I may have messed up with the internal refactoring causing an xml response to be given instead of json.

Will look into it when I get home later today.

**Comment by ReIaxo** [comment] 2024-01-06 14:26
It occurs in 6.0.0 and 5.0.1

You mean like this: 
```c#
Query.TraceSource.Switch.Level = System.Diagnostics.SourceLevels.All;
JsonUtils.TraceSource.Switch.Level = System.Diagnostics.SourceLevels.All;
```

The response looks "unnormal" for Calvin Harris. It is xml instead of json. Output is from 6.0.0.

```
MetaBrainz.MusicBrainz Verbose: 1 : WEB SERVICE REQUEST: GET https://musicbrainz.org/ws/2/artist/8dd98bdc-80ec-4e93-8509-2f46bafc09a7?inc=url-rels
MetaBrainz.MusicBrainz Verbose: 2 : HEADERS: <<
  Accept: application/json
  User-Agent: Add_Events_using_yambs/0.1 (mailto:email) MetaBrainz.MusicBrainz/6.0.0.0 (https://github.com/Zastai/MetaBrainz.MusicBrainz)
>>
MetaBrainz.MusicBrainz Verbose: 3 : NO BODY
MetaBrainz.MusicBrainz Verbose: 4 : WEB SERVICE RESPONSE: 200/OK 'OK' (v1.1)
MetaBrainz.MusicBrainz Verbose: 5 : HEADERS: <<
  Date: Sat, 06 Jan 2024 14:18:12 GMT
  Transfer-Encoding: chunked
  Connection: keep-alive
  Keep-Alive: timeout=15
  Vary: Accept-Encoding
  X-RateLimit-Limit: 1200
  X-RateLimit-Remaining: 883
  X-RateLimit-Reset: 1704550693
  Server: Plack::Handler::Starlet
  ETag: "2738c07e48f394363e467f4c7d6041cb"
  Access-Control-Allow-Origin: *
  X-Cache-Status: STALE
>>
MetaBrainz.MusicBrainz Verbose: 6 : CONTENT (application/xml; charset=utf-8): 13703 bytes
MetaBrainz.Common.Json.JsonUtils Verbose: 1 : JSON CONTENT: <?xml version="1.0" encoding="UTF-8"?>
<metadata xmlns="http://musicbrainz.org/ns/mmd-2.0#"><artist id="8dd98bdc-80ec-4e93-8509-2f46bafc09a7" type="Person" type-id="b6e035f4-3ce9-331c-97df-83397230b0df"><name>Calvin Harris</name><sort-name>Harris, Calvin</sort-name><disambiguation>Scottish DJ and producer</disambiguation><ipi>00460645949</ipi><ipi-list><ipi>00460645949</ipi><ipi>00716562048</ipi></ipi-list><isni-list><isni>0000000114975878</isni></isni-list><gender id="36d3d30a-839d-3eda-8cb3-29be4384e4a9">Male</gender><area id="6fa1c7da-6689-4cec-85f9-680f853e8a08"><name>Scotland</name><sort-name>Scotland</sort-name><iso-3166-2-code-list><iso-3166-2-code>GB-SCT</iso-3166-2-code></iso-3166-2-code-list></area><begin-area id="8e7708ce-f3fc-4e70-aae5-e8d47741389c"><name>Dumfries</name><sort-name>Dumfries</sort-name></begin-area><life-span><begin>1984-01-17</begin></life-span><relation-list target-type="url"><relation type="allmusic" type-id="6b3e3c85-0002-4f34-aca6-80ace0d7e846"><target id="8a07ab24-7599-4c72-bae2-bb17034f3dd7">https://www.allmusic.com/artist/mn0000945951</target><direction>forward</direction></relation><relation type="bandsintown" type-id="ea45ed3d-2d5e-456e-8c32-94b6f51426e2"><target id="93d1c528-e113-4fba-9f9a-810713e644dc">https://www.bandsintown.com/a/4733</target><direction>forward</direction></relation><relation type="BBC Music page" type-id="d028a975-000c-4525-9333-d3c8425e4b54"><target id="e9bb24de-24e7-4ed9-8746-2855bfd726fc">https://www.bbc.co.uk/music/artists/8dd98bdc-80ec-4e93-8509-2f46bafc09a7</target><direction>forward</direction><end>2020-11-19</end><ended>true</ended></relation><relation type="discogs" type-id="04a5b104-a4c2-4bac-99a1-7b837c37d9e4"><target id="a2a4937d-7fe0-48c4-a6c0-a65aa1bf67f5">https://www.discogs.com/artist/222578</target><direction>forward</direction></relation><relation type="free streaming" type-id="769085a1-c2f7-4c24-a532-2375a77693bd"><target id="2bc71ec7-ae6b-481c-a514-5bad3a9912ee">https://music.migu.cn/v3/music/artist/35721</target><direction>forward</direction></relation><relation type="free streaming" type-id="769085a1-c2f7-4c24-a532-2375a77693bd"><target id="37860678-d920-4a75-b9c5-1415fc7b9a13">https://open.spotify.com/artist/7CajNmpbOovFoOoasH2HaY</target><direction>forward</direction></relation><relation type="free streaming" type-id="769085a1-c2f7-4c24-a532-2375a77693bd"><target id="49938477-3da0-4ae4-bc41-85c0186e1354">https://www.deezer.com/artist/12178</target><direction>forward</direction></relation><relation type="image" type-id="221132e9-e30e-43f2-a741-15afc4c5fa7c"><target id="1854a4a9-d86d-4432-b1e1-2545fdcac30f">https://commons.wikimedia.org/wiki/File:Calvin_Harris_-_Rock_in_Rio_Madrid_2012_-_03.jpg</target><direction>forward</direction></relation><relation type="IMDb" type-id="94c8b0cc-4477-4106-932c-da60e63de61c"><target id="7b86eb7b-f597-4bd1-9f39-e694aadfbec1">https://www.imdb.com/name/nm2744713/</target><direction>forward</direction></relation><relation type="last.fm" type-id="08db8098-c0df-4b78-82c3-c8697b4bba7f"><target id="c1928b2d-87f9-4d9d-8514-f164b4d56bb3">https://www.last.fm/music/Calvin+Harris</target><direction>forward</direction></relation><relation type="lyrics" type-id="e4d73442-3762-45a8-905c-401da65544ed"><target id="501e46ce-025a-4343-ad20-336fde465688">http://muzikum.eu/en/122-6729/calvin-harris/lyrics.html</target><direction>forward</direction></relation><relation type="lyrics" type-id="e4d73442-3762-45a8-905c-401da65544ed"><target id="3a7b6e99-3fcf-4ce2-b0da-45b9b6c5931a">https://genius.com/artists/Calvin-harris</target><direction>forward</direction></relation><relation type="lyrics" type-id="e4d73442-3762-45a8-905c-401da65544ed"><target id="1b5afb83-841e-4612-9958-f1d298779e5f">https://www.musixmatch.com/artist/Calvin-Harris</target><direction>forward</direction></relation><relation type="lyrics" type-id="e4d73442-3762-45a8-905c-401da65544ed"><target id="ed61a71a-b2f6-464f-912a-24f54a4f0bb4">http://www.directlyrics.com/calvin-harris-artist.html</target><direction>forward</direction></relation><relation type="myspace" type-id="bac47923-ecde-4b59-822e-d08f0cd10156"><target id="60a1e442-f7e6-4048-a6a9-08449cda8467">https://myspace.com/calvinharristv</target><direction>forward</direction></relation><relation type="official homepage" type-id="fe33d22f-c3b0-4d68-bd53-a856badf2b15"><target id="029eb48d-aff3-4539-9e45-8d02d45a6fc9">http://www.calvinharris.com/</target><direction>forward</direction></relation><relation type="online community" type-id="35b3a50f-bf0e-4309-a3b4-58eeed8cee6a"><target id="330e939c-426d-4933-86e8-ffe2b3f07afb">http://equipboard.com/pros/calvin-harris</target><direction>forward</direction></relation><relation type="other databases" type-id="d94fb61c-fa20-4e3c-a19a-71a949fb2c55"><target id="0d85c2e5-8881-4529-bd04-c7b763410d1c">http://id.loc.gov/authorities/names/no2007146166</target><direction>forward</direction></relation><relation type="other databases" type-id="d94fb61c-fa20-4e3c-a19a-71a949fb2c55"><target id="8ca99765-9186-46c1-bb55-6483ec64516b">https://catalogue.bnf.fr/ark:/12148/cb15516628d</target><direction>forward</direction></relation><relation type="other databases" type-id="d94fb61c-fa20-4e3c-a19a-71a949fb2c55"><target id="bb2fab42-d1a1-4b76-b6e5-67c67a4de9bd">https://d-nb.info/gnd/135515548</target><direction>forward</direction></relation><relation type="other databases" type-id="d94fb61c-fa20-4e3c-a19a-71a949fb2c55"><target id="b13e09fb-6ea6-4362-95d7-2ab903157db5">https://imvdb.com/n/calvin-harris</target><direction>forward</direction></relation><relation type="other databases" type-id="d94fb61c-fa20-4e3c-a19a-71a949fb2c55"><target id="84139cd2-2dac-4e73-9a92-23f551a111ac">http://snaccooperative.org/ark:/99166/w6zq21zg</target><direction>forward</direction></relation><relation type="other databases" type-id="d94fb61c-fa20-4e3c-a19a-71a949fb2c55"><target id="21077a75-0de4-4c29-816b-d5a43dfd9b0a">https://rateyourmusic.com/artist/calvin-harris</target><direction>forward</direction></relation><relation type="other databases" type-id="d94fb61c-fa20-4e3c-a19a-71a949fb2c55"><target id="e73cd26a-dcbe-4ed7-8d8e-e38f2716040d">https://www.musik-sammler.de/artist/calvin-harris/</target><direction>forward</direction></relation><relation type="other databases" type-id="d94fb61c-fa20-4e3c-a19a-71a949fb2c55"><target id="cc395a96-74c6-48a4-a621-c7949a2a4d3a">https://www.muziekweb.nl/Link/M00000298166/POPULAR/</target><direction>forward</direction></relation><relation type="other databases" type-id="d94fb61c-fa20-4e3c-a19a-71a949fb2c55"><target id="58f6db6b-ec36-49c4-bba8-85de02cb9b75">https://www.whosampled.com/Calvin-Harris/</target><direction>forward</direction></relation><relation type="other databases" type-id="d94fb61c-fa20-4e3c-a19a-71a949fb2c55"><target id="fcf6b347-0458-4f3a-98e8-fd47e2754488">https://www.worldcat.org/identities/lccn-no2007146166/</target><direction>forward</direction></relation><relation type="other databases" type-id="d94fb61c-fa20-4e3c-a19a-71a949fb2c55"><target id="3a2cf4f9-8c98-417c-881a-6fddba4277a9">http://www.maniadb.com/artist/138523</target><direction>forward</direction></relation><relation type="purchase for download" type-id="f8319a2f-f824-4617-81c8-be6560b3b203"><target id="6976657f-06fc-45f7-bda3-d74cfd954158">https://play.google.com/store/music/artist?id=Avwbbklu2vufocv7d7ccglejzq4</target><direction>forward</direction><end>2020-10-12</end><ended>true</ended></relation><relation type="purchase for download" type-id="f8319a2f-f824-4617-81c8-be6560b3b203"><target id="7d55122a-4564-41e2-bff3-c4972dff7c16">https://itunes.apple.com/gb/artist/id201955086</target><direction>forward</direction></relation><relation type="purchase for download" type-id="f8319a2f-f824-4617-81c8-be6560b3b203"><target id="4b1dcc8b-07ea-4130-93be-73a21e0caa95">https://mora.jp/artist/37579/all</target><direction>forward</direction></relation><relation type="purchase for download" type-id="f8319a2f-f824-4617-81c8-be6560b3b203"><target id="b3a82bc1-b8f3-450b-bfc3-3b8c4e116101">https://music.apple.com/gb/artist/201955086</target><direction>forward</direction></relation><relation type="purchase for download" type-id="f8319a2f-f824-4617-81c8-be6560b3b203"><target id="aff35ed8-2b81-42cf-9601-b23b4e4d7a26">https://uk.7digital.com/artist/calvin-harris</target><direction>forward</direction></relation><relation type="purchase for download" type-id="f8319a2f-f824-4617-81c8-be6560b3b203"><target id="bff00fd0-28c1-4d16-adbc-4c1f52235f5c">https://www.beatport.com/artist/calvin-harris/32576</target><direction>forward</direction></relation><relation type="purchase for download" type-id="f8319a2f-f824-4617-81c8-be6560b3b203"><target id="1592c927-ef53-4b49-876d-74bde38e7da1">https://www.junodownload.com/artists/Calvin+Harris/</target><direction>forward</direction></relation><relation type="purchase for download" type-id="f8319a2f-f824-4617-81c8-be6560b3b203"><target id="a7972683-12cf-4c17-b088-ce4128954c88">https://www.qobuz.com/gb-en/interpreter/calvin-harris/40726</target><direction>forward</direction></relation><relation type="secondhandsongs" type-id="79c5b84d-a206-4f4c-9832-78c028c312c3"><target id="0b7a2f88-055e-41ea-8702-7d5827751589">https://secondhandsongs.com/artist/29187</target><direction>forward</direction></relation><relation type="setlistfm" type-id="bf5d0d5e-27a1-4e94-9df7-3cdc67b3b207"><target id="a4c813d9-5887-4f1c-8f22-f128f94f3725">https://www.setlist.fm/setlists/calvin-harris-4bd667a6.html</target><direction>forward</direction></relation><relation type="social network" type-id="99429741-f3f6-484b-84f8-23af51991770"><target id="c3fc2551-b19f-4484-a52f-2ad60c07d967">https://plus.google.com/+CalvinHarris</target><direction>forward</direction><end>2019-04</end><ended>true</ended></relation><relation type="social network" type-id="99429741-f3f6-484b-84f8-23af51991770"><target id="dad00cf9-7b18-4784-9594-7ab5b3ba90b2">https://twitter.com/CalvinHarris</target><direction>forward</direction></relation><relation type="social network" type-id="99429741-f3f6-484b-84f8-23af51991770"><target id="d8e51939-eaf3-47da-b282-879e942468b3">https://vk.com/calvinharris</target><direction>forward</direction></relation><relation type="social network" type-id="99429741-f3f6-484b-84f8-23af51991770"><target id="c416d778-a086-441a-a291-7b355ef6fe6f">https://www.facebook.com/calvinharris</target><direction>forward</direction></relation><relation type="social network" type-id="99429741-f3f6-484b-84f8-23af51991770"><target id="06f3873a-53b9-4415-a0d9-1309399f946e">https://www.instagram.com/calvinharris/</target><direction>forward</direction></relation><relation type="social network" type-id="99429741-f3f6-484b-84f8-23af51991770"><target id="cb8b9071-8c2c-4ddd-894b-2d566fbb39eb">https://www.tiktok.com/@calvinharris</target><direction>forward</direction></relation><relation type="songkick" type-id="aac9c4bc-a5b9-30b8-9839-e3ac314c6e58"><target id="92e168e8-6d5c-4488-bd42-dd9690fd9577">https://www.songkick.com/artists/82547</target><direction>forward</direction></relation><relation type="soundcloud" type-id="89e4a949-0976-440d-bda1-5f772c1e5710"><target id="fca952fc-1262-4d1c-9309-975db81d18ea">https://soundcloud.com/calvinharris</target><direction>forward</direction></relation><relation type="streaming" type-id="63cc5d1f-f096-4c94-a43f-ecb32ea94161"><target id="a95b2ba0-10c9-41d7-bda4-d3eb1205cc23">https://music.amazon.com/artists/B001Q9UIDS</target><direction>forward</direction></relation><relation type="streaming" type-id="63cc5d1f-f096-4c94-a43f-ecb32ea94161"><target id="407b20d8-e4f6-4bf5-bd69-003622b92d5d">https://music.apple.com/de/artist/201955086</target><direction>forward</direction></relation><relation type="streaming" type-id="63cc5d1f-f096-4c94-a43f-ecb32ea94161"><target id="b3a82bc1-b8f3-450b-bfc3-3b8c4e116101">https://music.apple.com/gb/artist/201955086</target><direction>forward</direction></relation><relation type="streaming" type-id="63cc5d1f-f096-4c94-a43f-ecb32ea94161"><target id="b6733dac-2292-4659-8cf7-62ce91e7a671">https://tidal.com/artist/8401</target><direction>forward</direction></relation><relation type="streaming" type-id="63cc5d1f-f096-4c94-a43f-ecb32ea94161"><target id="db2d0607-b41a-4104-9d12-3b099f3ce6cf">https://us.napster.com/artist/calvin-harris</target><direction>forward</direction></relation><relation type="streaming" type-id="63cc5d1f-f096-4c94-a43f-ecb32ea94161"><target id="a7972683-12cf-4c17-b088-ce4128954c88">https://www.qobuz.com/gb-en/interpreter/calvin-harris/40726</target><direction>forward</direction></relation><relation type="VIAF" type-id="e8571dcc-35d4-4e91-a577-a3382fd84460"><target id="2174d689-77e5-406a-b8d7-d060277f6c68">http://viaf.org/viaf/120113854</target><direction>forward</direction></relation><relation type="wikidata" type-id="689870a4-a1e4-4912-b17f-7b2664215698"><target id="519378dc-28a1-4d6c-a244-9e650897f1f3">https://www.wikidata.org/wiki/Q81637</target><direction>forward</direction></relation><relation type="youtube" type-id="6a540e5b-58c6-4192-b6ba-dbc71ec8fcf0"><target id="7de67438-978e-4a90-a892-ce77816e106d">https://www.youtube.com/user/CalvinHarrisVEVO</target><direction>forward</direction></relation><relation type="youtube" type-id="6a540e5b-58c6-4192-b6ba-dbc71ec8fcf0"><target id="82a9f4f7-133f-439f-9ccb-cf5f300ecd42">https://www.youtube.com/user/icreateddisco</target><direction>forward</direction></relation><relation type="youtube music" type-id="631712a0-7525-42ba-b7a3-605aa7a238c4"><target id="2dac0dba-74bc-41b7-b2bf-21a3975763f8">https://music.youtube.com/channel/UCZ0Aezmtk-S2l8A9Ln-2lKw</target><direction>forward</direction></relation></relation-list></artist></metadata>
```

**Comment by Zastai** [comment] 2024-01-06 15:50
Ah, if it's in 5.0.1 too, then it looks like a bug on the MusicBrainz site. And the accept header definitely asks for json.

**Comment by ReIaxo** [comment] 2024-01-06 15:57
Looks like. But maybe you should test it by yourself when you have the time, just to be sure.

Will you reach out then to the MusicBrainz team or should I? I think you are deeper into it and you can explain it better.

**Comment by Zastai** [comment] 2024-01-06 16:00
Looks like it's specific to asking for URL relationships; any other request returns JSON like it should.
I'll log a ticket with MusicBrainz.

**Comment by Zastai** [comment] 2024-01-06 16:26
https://tickets.metabrainz.org/browse/MBS-13436

**Comment by Zastai** [comment] 2024-01-06 16:40
Looks like it's working again; can you confirm?

**Comment by ReIaxo** [comment] 2024-01-06 16:51
No, same as before. For me it looks like it works for some artists and for some not. Some requests work even if relations are included.

**Comment by Zastai** [comment] 2024-01-06 16:55
Very strange - I could reproduce it for your sample request 100% of the time. But not anymore.

**Comment by Zastai** [comment] 2024-01-07 22:54
Could you try with a NuGet package from [the PR build](https://github.com/Zastai/MetaBrainz.MusicBrainz/actions/runs/7441206426) and see if that resolves your issue?

**Comment by ReIaxo** [comment] 2024-01-08 22:01
Thought it is a MusicBrainz issue?

But yeah, it works. Double checked with the old version, which still gets the json errors.

Thank you for fixing.

**Comment by Zastai** [comment] 2024-01-08 22:32
Well it _is_ a server issue. But you can ask for json in two ways: via the `Accept` header, as I was doing, and by adding `?fmt=json` to the request. With this change, I do both.

**Comment by Zastai** [comment] 2024-01-10 21:10
MusicBrainz say they have fixed this on the server side (caching issue). If you can confirm that with 5.0.1 or 6.0.0, @ReIaxo, I will hold off on making a new release until more features have landed.

**Comment by ReIaxo** [comment] 2024-01-11 07:36
Cool. I can confirm, that I get no errors with 5.0.1, 6.0.0 and with the preview. It is ok for me when you hold a new release back.

Thank you very much for the good collaboration.

**Closed** 2024-01-19 22:51 UTC
Labels: bug
